remote_theme: pages-themes/midnight@v0.2.0

show_downloads: false
title: James LaFritz
tagline: Let's connect, collaborate, and build something amazing!
description: Game Developer specializing in Unity, C#, and performance-driven 2D/3D gameplay systems | Published Tech Writer